import { AppColors, Colors, screenHeight, screenWidth } from "@/utils/Constants";
import { Platform, StyleSheet } from "react-native";
import {
  RFValue,
  scaleHorizontal,
  scaleModerate,
  scaleVertical,
} from "@/utils/responsive";

export const createRideStyles = (c: AppColors = Colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    backButton: {
      position: "absolute",
      top: Platform.OS === "android" ? scaleVertical(20) : scaleVertical(60),
      left: scaleHorizontal(10),
      backgroundColor: c.surface,
      borderRadius: scaleModerate(100),
      justifyContent: "center",
      alignItems: "center",
      shadowOffset: { width: 1, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      shadowColor: c.text,
      elevation: 10,
      height: scaleModerate(40),
      width: scaleModerate(40),
    },
    couponContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: scaleHorizontal(15),
      width: "50%",
      left: scaleHorizontal(-10),
      paddingHorizontal: scaleHorizontal(10),
      marginVertical: scaleVertical(10),
    },
    icon: {
      width: scaleModerate(40),
      height: scaleModerate(40),
      resizeMode: "contain",
    },
    bookingContainer: {
      shadowOffset: { width: 1, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      shadowColor: c.text,
      elevation: 10,
      justifyContent: "center",
      alignItems: "center",
      padding: scaleModerate(10),
      backgroundColor: c.surface,
      position: "absolute",
      bottom: 0,
      borderTopLeftRadius: scaleModerate(20),
      borderTopRightRadius: scaleModerate(20),
      width: "100%",
    },
    rideSelectionContainer: {
      borderTopLeftRadius: scaleModerate(20),
      height: screenHeight * 0.55,
      borderTopRightRadius: scaleModerate(20),
      shadowOffset: { width: 1, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      shadowColor: c.text,
      elevation: 10,
      width: screenWidth,
      backgroundColor: c.surface,
      justifyContent: "center",
      alignItems: "center",
    },
    rideIcon: {
      width: scaleModerate(30),
      height: scaleModerate(30),
      resizeMode: "contain",
    },
    scrollContainer: {
      paddingBottom: scaleVertical(160),
      width: screenWidth,
      borderColor: c.muted,
      paddingHorizontal: scaleHorizontal(10),
    },
    rideOption: {
      width: "100%",
      padding: scaleModerate(15),
      borderRadius: scaleModerate(12),
      marginVertical: scaleVertical(5),
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    rideDetails: {
      width: "70%",
    },
    priceContainer: {
      alignItems: "flex-end",
    },
    fastestLabel: {
      color: c.tertiary,
      fontSize: RFValue(10),
      marginLeft: scaleHorizontal(5),
    },
    discountedPrice: {
      textDecorationLine: "line-through",
      color: c.muted,
      fontSize: RFValue(12),
    },
    offerText: {
      textAlign: "center",
    },
    offerContainer: {
      paddingVertical: scaleVertical(15),
      borderBottomWidth: 1,
      width: "100%",
      borderColor: c.border,
      marginBottom: scaleVertical(10),
    },
    headerContainer: {
      borderBottomWidth: 2,
      borderColor: c.border,
      flexDirection: "row",
      justifyContent: "space-between",
      padding: scaleModerate(10),
    },
    pinIcon: {
      width: scaleModerate(20),
      height: scaleModerate(20),
      resizeMode: "contain",
    },
    bottomButtonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: scaleHorizontal(15),
      paddingVertical: scaleVertical(10),
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    cancelButton: {
      flex: 1,
      marginRight: scaleHorizontal(10),
      backgroundColor: c.secondary,
      paddingVertical: scaleVertical(12),
      borderRadius: scaleModerate(12),
      alignItems: "center",
    },
    cancelButtonText: {
      color: c.danger,
    },
    backButton2: {
      flex: 1,
      marginLeft: scaleHorizontal(10),
      backgroundColor: c.primary,
      paddingVertical: scaleVertical(12),
      borderRadius: scaleModerate(12),
      alignItems: "center",
    },
    backButtonText: {
      color: c.onPrimary,
    },
    swipeableContaniner: {
      position: "absolute",
      width: "100%",
      padding: scaleModerate(10),
      backgroundColor: c.surface,
      shadowOffset: { width: 1, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      bottom: 0,
      paddingBottom: Platform.OS === "ios" ? scaleVertical(30) : scaleVertical(10),
      shadowColor: c.text,
      elevation: 10,
      borderTopLeftRadius: scaleModerate(20),
      borderTopRightRadius: scaleModerate(20),
    },
    swipeableContaninerRider: {
      width: "100%",
      padding: scaleModerate(10),
      backgroundColor: c.surface,
      shadowOffset: { width: 1, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      paddingBottom: Platform.OS === "ios" ? scaleVertical(30) : scaleVertical(10),
      shadowColor: c.text,
      elevation: 10,
      borderTopLeftRadius: scaleModerate(20),
      borderTopRightRadius: scaleModerate(20),
    },
    swipeButtonContainer: {
      borderRadius: scaleModerate(2),
      height: scaleVertical(50),
      borderWidth: 0,
    },
    railStyles: {
      backgroundColor: "rgba(255,255,255,0.6)",
      height: scaleVertical(50),
      borderRadius: 0,
      borderWidth: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    titleStyles: {
      fontWeight: "700",
    },
    thumbIconStyles: {
      borderRadius: scaleModerate(5),
      height: scaleVertical(50),
      backgroundColor: c.primary,
    },
  });

export let rideStyles = createRideStyles();
export const rebuildRideStyles = (c: AppColors) => {
  rideStyles = createRideStyles(c);
};
